name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --include dev

      - name: Set up Vault
        run: npx install-vault-cli

      - name: Run tests
        run: npx ava
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

  vault-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --include dev

      - name: Set up Vault
        run: npx run-vault mynth-helper
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Verify secrets are loaded
        run: |
          export VAULT_CLI_TOKEN="$(docker exec vault token)"
          output=$(vault-cli get mynth-helper/test my_secret)
          if [ "$output" != "4a72ff1fab93287fb9f741e9412f1677" ]; then
            echo "Output does not match expected value"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --include dev

      - name: Lint
        run: npm run lint

  validate-markdown:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --include dev

      - name: Setup Pandoc
        run: sudo apt-get install -y pandoc

      - name: Validate markdown
        run: npx format-md --check

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18
          check-latest: true

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --include dev

      - name: Validate TypeScript
        run: npm run build
